import type {
  Blog,
  BodySystem,
  Category,
  MedicalProfession,
  SiteSettings,
  SurveyQuestion,
} from './types';

const uid = (s: string) =>
  // deterministic fake uuid so fallback rows are stable
  `fb-${s}-${'00000000'.slice(s.length)}`;

export const fallbackCategories: Category[] = [
  { id: uid('mh'), slug: 'mental-health', name: 'Mental Health', icon: 'Brain', accent: 'hotpink', tagline: 'Tools for a kinder, calmer mind.', sort_order: 1 },
  { id: uid('an'), slug: 'anxiety', name: 'Anxiety & Stress', icon: 'Wind', accent: 'teal', tagline: 'Breathe easier when worries get loud.', sort_order: 2 },
  { id: uid('sl'), slug: 'sleep', name: 'Sleep', icon: 'Moon', accent: 'navy', tagline: 'Rest is productive. Let us get you there.', sort_order: 3 },
  { id: uid('wt'), slug: 'weight', name: 'Weight & Movement', icon: 'Activity', accent: 'sunny', tagline: 'Gentle, joyful ways to move your body.', sort_order: 4 },
  { id: uid('he'), slug: 'healthy-eating', name: 'Healthy Eating', icon: 'Apple', accent: 'teal', tagline: 'Fuel that feels good and tastes amazing.', sort_order: 5 },
  { id: uid('se'), slug: 'self-esteem', name: 'Self-Esteem', icon: 'Heart', accent: 'hotpink', tagline: 'You are worthy, exactly as you are.', sort_order: 6 },
  { id: uid('fo'), slug: 'focus', name: 'Focus & Motivation', icon: 'Target', accent: 'sunny', tagline: 'Find your spark and keep it glowing.', sort_order: 7 },
  { id: uid('re'), slug: 'relationships', name: 'Relationships', icon: 'Users', accent: 'navy', tagline: 'Connection, boundaries, and belonging.', sort_order: 8 },
];

const blogSeed: Array<
  Omit<Blog, 'category_id' | 'category'> & { catSlug: string }
> = [
  { catSlug: 'mental-health', id: uid('b1'), slug: 'a-kinder-voice', title: 'A Kinder Voice for the Voice in Your Head', summary: 'When your inner critic gets loud, here are gentle ways to turn the volume down and speak to yourself like a friend.', body: 'We all have an inner voice — sometimes it cheers us on, and sometimes it says things we\'d never say to a friend. The good news? You can teach that voice to be kinder.## Notice the narrator\nNext time a harsh thought shows up, pause and name it: "There\'s the critic again." Naming creates distance. You are not the thought; you are the one noticing it.## Talk to yourself like a teammate\nImagine a friend messed up. You\'d probably say, "It\'s okay, you\'ll get it next time." Try saying that to yourself. It feels silly at first and that\'s the point — kindness takes practice.## The 3-to-1 rule\nFor every critical thought, add three honest compliments. They don\'t have to be huge. "I asked for help today" counts. "I kept showing up" counts.## Tiny proof, big shift\nCollect small wins in your phone notes. Over a week, a pattern appears: you\'re already doing more right than your critic admits.## You Got This\nChanging how you talk to yourself won\'t happen overnight. But each kind sentence rewires the next one. Start with one today.', author: 'Dr. Maya Chen', read_minutes: 4, cover_url: null, accent: 'hotpink', published: true, featured: true, created_at: new Date().toISOString() },
  { catSlug: 'mental-health', id: uid('b2'), slug: 'low-mood-what-helps', title: 'When the Low Days Come: What Actually Helps', summary: 'Sad days are part of being human. This guide walks through small, doable steps that lift you without pretending everything is fine.', body: 'Some days feel heavy before they even start. You don\'t have to fix everything — you just need one next step.## Name it without judging it\nLow mood isn\'t a failure. Tell yourself: "I\'m having a hard day, and that\'s okay." Naming it shrinks the shame around it.## Move one degree\nYou don\'t need a full workout. Stretch for two minutes. Walk to the kitchen for water. Tiny movement tells your body, "I\'m taking care of you."## Tell one person\nIsolation feeds low mood. Text one safe person something honest: "Rough day. Just wanted to say hi." Connection is medicine.## Feed the basics\nSleep, water, food, daylight. When these slip, mood slips with them. Fix one before you fix everything.## When to ask for more\nIf low days stack up for two weeks or more, tell a trusted adult or doctor. Reaching out is strength, not weakness.## You Got This\nYou\'re not behind. You\'re just on a hard part of the path — and the path keeps going.', author: 'MY Journal Team', read_minutes: 5, cover_url: null, accent: 'hotpink', published: true, featured: false, created_at: new Date().toISOString() },
  { catSlug: 'anxiety', id: uid('b3'), slug: 'the-4-7-8-breath', title: 'The 4-7-8 Breath: A Reset You Can Carry Everywhere', summary: 'A 60-second breathing pattern that calms your nervous system. Learn why it works and how to use it in the moments you need it most.', body: 'When anxiety spikes, your body thinks there\'s danger. Breathing is the remote control that tells it, "We\'re safe."## Why it works\nLong exhales switch on your calming (parasympathetic) nervous system. It\'s biology, not magic — but it feels a little magical.## The pattern\nBreathe in through your nose for 4 seconds. Hold for 7. Exhale slowly through your mouth for 8. Do this four times.## Make it yours\nTry it before a test, before sleep, or when your chest feels tight. There\'s no wrong time to reset.## A small twist\nIf 7-second holds feel tough, start with 4-4-6 and build up. The goal is ease, not a perfect score.## You Got This\nYou can\'t always control the worry, but you can always reach for one slow breath.', author: 'MY Journal Team', read_minutes: 3, cover_url: null, accent: 'teal', published: true, featured: true, created_at: new Date().toISOString() },
  { catSlug: 'anxiety', id: uid('b4'), slug: 'worry-time-trick', title: 'The "Worry Time" Trick That Actually Works', summary: 'Give your worries a scheduled appointment and watch them lose their grip on the rest of your day.', body: 'Telling yourself "don\'t worry" never works. This does.## Set a worry window\nPick 15 minutes a day — say 6:00pm — as official Worry Time. When a worry pops up earlier, jot it down and tell it, "See you at 6."## Why this helps\nYou\'re not suppressing the worry; you\'re scheduling it. Your brain learns the worry will be heard, so it stops shouting all day.## During the window\nLook at your list. Some worries will feel smaller already. For the real ones, ask: "Is this solvable? If yes, what\'s one step? If no, can I let it sit?"## Keep it short\nCap it at 15 minutes. Worry Time shouldn\'t become Worry Evening.## You Got This\nYou\'re the boss of your worries, not the other way around. They just don\'t know it yet.', author: 'Dr. Maya Chen', read_minutes: 4, cover_url: null, accent: 'teal', published: true, featured: false, created_at: new Date().toISOString() },
  { catSlug: 'sleep', id: uid('b5'), slug: 'wind-down-routine', title: 'Build a Wind-Down Routine That Sticks', summary: 'Your brain needs a signal that the day is done. Here\'s how to design a 30-minute routine you\'ll actually look forward to.', body: 'Good sleep starts before you\'re tired. A routine is the bridge.## Pick a start time\nCount back 8 hours from when you need to wake up. Subtract 30 more — that\'s wind-down time.## The 3-part bridge\n1) Dim the lights and screens. 2) Do something gentle (stretch, read, sketch). 3) One calming breath before you lie down.## Make it cozy\nA favorite hoodie, dim lamp, quiet playlist. Comfort cues tell your body it\'s safe to let go.## The screen rule\nIf you can\'t ditch the phone, switch it to night mode and put it face-down. Blue light tricks your brain into thinking it\'s daytime.## When you can\'t sleep\nDon\'t force it. Get up, do something boring in dim light, come back when your eyes feel heavy.## You Got This\nSleep isn\'t a performance. It\'s a gift you give your tomorrow-self.', author: 'MY Journal Team', read_minutes: 5, cover_url: null, accent: 'navy', published: true, featured: true, created_at: new Date().toISOString() },
  { catSlug: 'sleep', id: uid('b6'), slug: 'why-you-cant-sleep', title: 'Why You Can\'t Sleep (And It\'s Not Your Fault)', summary: 'Late nights, racing thoughts, phone scrolling — here\'s what\'s really going on and the small fixes that help.', body: 'If sleep feels impossible, there\'s usually a reason — and a fix.## The circadian clock\nYour body runs on a 24-hour rhythm. Light in the morning sets it; light at night scrambles it. Morning sunlight is free sleep medicine.## Caffeine math\nCaffeine can stay in your system 6+ hours. A 4pm soda can haunt you at 10pm. Cut caffeine after lunch.## Racing thoughts\nKeep a "brain dump" notebook by your bed. Write tomorrow\'s to-dos before your head hits the pillow — then they\'re not your job until morning.## The 20-minute rule\nIf you\'re still awake after 20 minutes, leave the bed. Staying there teaches your brain that bed = frustration.## You Got This\nSleep is a skill. You\'re allowed to learn it.', author: 'MY Journal Team', read_minutes: 4, cover_url: null, accent: 'navy', published: true, featured: false, created_at: new Date().toISOString() },
  { catSlug: 'weight', id: uid('b7'), slug: 'joyful-movement', title: 'Joyful Movement: Exercise That Doesn\'t Feel Like Punishment', summary: 'Movement doesn\'t have to mean misery. Discover ways to move that make you feel alive, not depleted.', body: 'Forget "no pain no gain." Joyful movement is the sustainable kind.## Redefine exercise\nDance in your room counts. Walking while calling a friend counts. Stretching during a show counts. If it moves you and feels good, it counts.## The 10-minute deal\nTell yourself you\'ll move for just 10 minutes. If you want to stop after, stop. Most days you\'ll keep going — momentum is sneaky.## Pair it with joy\nMove to music you love, with people you like, in places that make you smile. Your brain starts linking movement with good feelings.## Listen to your body\nSoreness is info, not a badge. Rest is part of movement, not the opposite of it.## You Got This\nYour body wants to move. The right kind is the kind you\'ll actually do.', author: 'MY Journal Team', read_minutes: 4, cover_url: null, accent: 'sunny', published: true, featured: true, created_at: new Date().toISOString() },
  { catSlug: 'weight', id: uid('b8'), slug: 'your-body-isnt-a-problem', title: 'Your Body Isn\'t a Problem to Be Solved', summary: 'A compassionate look at body image, the messages we absorb, and how to build a kinder relationship with the body you have.', body: 'You weren\'t born hating your body. You learned it. You can learn something kinder.## Where the noise comes from\nAds, comments, comparisons — they\'re not your voice. They\'re echoes. You don\'t have to keep echoing them.## What bodies actually do\nBodies breathe, heal, hug, carry you upstairs, feel sunlight. They\'re doing a thousand jobs right now. That\'s worth awe.## Unfollow the shame\nCurate your feed. Unfollow accounts that make you feel worse. Follow ones that show real bodies doing real things.## Talk to your body\nThank it for one thing today. "Thanks for getting me through that test." It sounds odd. It changes things.## You Got This\nYour body is your lifelong home. You get to decide how you treat it.', author: 'Dr. Maya Chen', read_minutes: 5, cover_url: null, accent: 'sunny', published: true, featured: false, created_at: new Date().toISOString() },
  { catSlug: 'healthy-eating', id: uid('b9'), slug: 'plate-not-perfect', title: 'The Plate, Not the Perfect: Easy Eating That Lasts', summary: 'Ditch the diet drama. Learn the simple "half plate" rule that makes healthy eating feel doable and delicious.', body: 'Eating well isn\'t about rules. It\'s about rhythm.## The half-plate idea\nFill half your plate with color — fruits or veggies. The other half is whatever you love. No food is banned.## Add, don\'t subtract\nInstead of "I can\'t have X," ask "What can I add?" Add a fruit to breakfast. Add veggies to dinner. Adding feels good; cutting feels bad.## Hunger is a friend\nEat when you\'re hungry. Stop when you\'re comfortably full. Both take practice, and that\'s normal.## Water is underrated\nMost of us feel tired or cranky when we\'re just thirsty. A glass of water before snacking is a small magic trick.## You Got This\nFood is fuel and joy. You can have both.', author: 'MY Journal Team', read_minutes: 4, cover_url: null, accent: 'teal', published: true, featured: true, created_at: new Date().toISOString() },
  { catSlug: 'healthy-eating', id: uid('b10'), slug: 'snacks-that-love-you-back', title: 'Snacks That Love You Back', summary: '12 easy snack ideas that give you steady energy instead of the sugar crash — with almost zero prep.', body: 'Snacks shouldn\'t make you crash 30 minutes later. Try these.## The steady-energy combo\nPair something with carbs (fruit, crackers) with something with protein or fat (nut butter, cheese, yogurt). The combo keeps you full.## 5 no-prep favorites\nApple + peanut butter. Yogurt + berries. Carrots + hummus. Trail mix. Cheese + grapes.## The 3pm slump fix\nMost people crash mid-afternoon. That\'s the perfect time for a combo snack — not a candy bar that makes it worse.## You Got This\nSnacking isn\'t cheating. It\'s strategy.', author: 'MY Journal Team', read_minutes: 3, cover_url: null, accent: 'teal', published: true, featured: false, created_at: new Date().toISOString() },
  { catSlug: 'self-esteem', id: uid('b11'), slug: 'you-are-not-your-grades', title: 'You Are Not Your Grades, Your Looks, or Your Followers', summary: 'A reminder that your worth isn\'t measured in numbers — and a practice for remembering it when the world says otherwise.', body: 'The world hands you a scoreboard. You don\'t have to play by it.## The scoreboard lie\nGrades, likes, weight, rank — they\'re numbers. They describe a slice, not the whole you. You are not a slice.## What worth actually is\nWorth isn\'t earned. It\'s the starting line, not the finish. You\'re worthy the day you\'re born and every day after.## The evidence list\nWrite down 5 things you like about yourself that have nothing to do with appearance or achievement. Kind to siblings? Funny? Curious? That\'s the real you.## When the scoreboard yells\nNotice the thought "I\'m only good if I achieve X." Add "and" — "and I\'m still worthy if I don\'t."## You Got This\nYou are the sky. The numbers are just weather.', author: 'Dr. Maya Chen', read_minutes: 4, cover_url: null, accent: 'hotpink', published: true, featured: true, created_at: new Date().toISOString() },
  { catSlug: 'self-esteem', id: uid('b12'), slug: 'comparison-thief', title: 'Comparison Is the Thief of Joy (Here\'s the Exit)', summary: 'Why comparing yourself to others always feels bad, and how to redirect that energy into something that helps.', body: 'Comparison feels like information. It\'s usually a trap.## Why it stings\nYou compare your behind-the-scenes to everyone else\'s highlight reel. It\'s not a fair fight.## The only fair comparison\nCompare yourself to you, one month ago. That\'s the only race that\'s honest.## Steal the spark\nInstead of "why them and not me," ask "what can I learn from them?" Turn envy into a roadmap.## Mute the triggers\nIf certain apps or people make you feel small, mute them. Your peace is worth more than their updates.## You Got This\nYour path is yours. Nobody else is walking it.', author: 'MY Journal Team', read_minutes: 3, cover_url: null, accent: 'hotpink', published: true, featured: false, created_at: new Date().toISOString() },
  { catSlug: 'focus', id: uid('b13'), slug: 'two-minute-start', title: 'The Two-Minute Start That Beats Procrastination', summary: 'When starting feels impossible, shrink the task until it\'s tiny — then watch momentum do the rest.', body: 'Procrastination isn\'t laziness. It\'s usually overwhelm. The fix is smallness.## Shrink the task\n"I need to study" feels huge. "I\'ll open the book and read one paragraph" feels doable. Pick the tiny version.## The 2-minute rule\nTell yourself you\'ll work for just 2 minutes. Anyone can do 2 minutes. Starting is the hard part; continuing is easier.## Remove the friction\nPut your phone in another room. Open the tab before you sit down. Make the good thing the easy thing.## Reward the start, not the finish\nCelebrating starting ("I opened it!") works better than waiting to celebrate completion.## You Got This\nYou don\'t have to finish. You just have to start.', author: 'MY Journal Team', read_minutes: 3, cover_url: null, accent: 'sunny', published: true, featured: true, created_at: new Date().toISOString() },
  { catSlug: 'focus', id: uid('b14'), slug: 'focus-environment', title: 'Design a Focus Environment That Actually Works', summary: 'Your space shapes your attention. Build a setup that makes focus the default and distraction the effort.', body: 'Willpower is unreliable. Environment wins.## The phone rule\nOut of sight, out of mind — literally. Your phone in your pocket drains focus even when it\'s off. Put it in another room.## One tab, one task\nBrowser tabs are open temptations. Close everything except what you\'re doing.## The focus soundtrack\nLo-fi, white noise, or rain — pick something without lyrics. Lyrics steal the language part of your brain.## The 25-5 rhythm\nWork 25 minutes, break 5. After 4 rounds, take a longer break. Known as Pomodoro, and it works because it\'s bounded.## You Got This\nFocus isn\'t a personality trait. It\'s a setup.', author: 'MY Journal Team', read_minutes: 4, cover_url: null, accent: 'sunny', published: true, featured: false, created_at: new Date().toISOString() },
  { catSlug: 'relationships', id: uid('b15'), slug: 'boundaries-without-guilt', title: 'Boundaries Without the Guilt Trip', summary: 'Saying no doesn\'t make you mean. Learn the scripts and mindset for setting limits that protect your peace.', body: 'Boundaries aren\'t walls. They\'re doors with locks — you choose who comes in.## The guilt is normal\nFeeling guilty after setting a boundary doesn\'t mean you did it wrong. It means you\'re practicing something new.## Simple scripts\n"I\'d love to, but I can\'t this time." "I need some quiet tonight." "That doesn\'t work for me." Short, kind, final.## You can\'t control their reaction\nSome people won\'t like your boundary. That\'s information, not instruction. Their reaction is theirs to manage.## Start small\nPractice with low-stakes no\'s — declining a plan, leaving a chat. The muscle grows.## You Got This\nSaying no to others is sometimes saying yes to yourself.', author: 'Dr. Maya Chen', read_minutes: 4, cover_url: null, accent: 'navy', published: true, featured: true, created_at: new Date().toISOString() },
  { catSlug: 'relationships', id: uid('b16'), slug: 'how-to-reach-out', title: 'How to Reach Out When You\'re Lonely', summary: 'Loneliness lies and tells you no one cares. Here\'s how to test that — gently, and one message at a time.', body: 'Loneliness is a feeling, not a fact. You can act anyway.## The lie it tells\nLoneliness whispers "no one wants to hear from you." It\'s almost always wrong. People are lonelier than they admit.## The low-stakes text\nPick one person. Send something small: "Saw this and thought of you," "How\'s your week?" No pressure, no big ask.## Accept the awkward\nReaching out feels awkward for everyone. Awkward is not the same as wrong.## Join a small thing\nA club, a volunteer shift, a class. Repeated low-pressure contact builds real connection over time.## You Got This\nYou are more wanted than loneliness lets you believe.', author: 'MY Journal Team', read_minutes: 4, cover_url: null, accent: 'navy', published: true, featured: false, created_at: new Date().toISOString() },
];

export const fallbackBlogs: Blog[] = blogSeed.map(({ catSlug, ...rest }) => {
  const cat = fallbackCategories.find((c) => c.slug === catSlug) ?? null;
  return {
    ...rest,
    category_id: cat?.id ?? null,
    category: cat,
  };
});

export const fallbackSurveyQuestions: SurveyQuestion[] = [
  { id: uid('q1'), category_id: fallbackCategories[0].id, category_slug: 'mental-health', question: 'How has your mood been feeling lately?', prompt: 'Pick the face that matches your week.', sort_order: 1 },
  { id: uid('q2'), category_id: fallbackCategories[1].id, category_slug: 'anxiety', question: 'How often do worries or stress get in your way?', prompt: 'There\'s no wrong answer — just honest.', sort_order: 2 },
  { id: uid('q3'), category_id: fallbackCategories[2].id, category_slug: 'sleep', question: 'How well are you sleeping these days?', prompt: 'Think about the last couple of weeks.', sort_order: 3 },
  { id: uid('q4'), category_id: fallbackCategories[3].id, category_slug: 'weight', question: 'How do you feel about moving your body?', prompt: 'Movement can be dancing, walking, anything joyful.', sort_order: 4 },
  { id: uid('q5'), category_id: fallbackCategories[4].id, category_slug: 'healthy-eating', question: 'How is your relationship with food right now?', prompt: 'Food is fuel, not a test.', sort_order: 5 },
  { id: uid('q6'), category_id: fallbackCategories[5].id, category_slug: 'self-esteem', question: 'How often do you feel good about yourself?', prompt: 'You deserve kindness — especially from you.', sort_order: 6 },
  { id: uid('q7'), category_id: fallbackCategories[6].id, category_slug: 'focus', question: 'How easy is it to focus on things you care about?', prompt: 'Distractions happen to everyone.', sort_order: 7 },
  { id: uid('q8'), category_id: fallbackCategories[7].id, category_slug: 'relationships', question: 'How connected do you feel to the people around you?', prompt: 'Connection looks different for everyone.', sort_order: 8 },
];

export const fallbackBodySystems: BodySystem[] = [
  { id: uid('s1'), slug: 'nervous', name: 'Nervous System', short: 'Your body\'s command center — the brain, spinal cord, and nerves that send messages at lightning speed.', what_it_does: ['Controls your thoughts, feelings, and movements', 'Carries signals between your brain and body', 'Stores memories and learns new things', 'Runs on electricity — tiny signals called nerve impulses'], fun_fact: 'Your brain sends messages at up to 268 miles per hour — faster than a race car!', accent: 'hotpink', sort_order: 1 },
  { id: uid('s2'), slug: 'circulatory', name: 'Circulatory System', short: 'A vast highway of blood vessels powered by your heart, delivering oxygen and nutrients everywhere.', what_it_does: ['Pumps blood through about 60,000 miles of vessels', 'Carries oxygen from your lungs to every cell', 'Delivers nutrients from food you eat', 'Helps fight off infections with white blood cells'], fun_fact: 'Your heart beats about 100,000 times a day — that\'s billions of beats in a lifetime.', accent: 'hotpink', sort_order: 2 },
  { id: uid('s3'), slug: 'respiratory', name: 'Respiratory System', short: 'How you breathe in oxygen and breathe out carbon dioxide — your lungs doing their quiet, essential work.', what_it_does: ['Brings fresh oxygen into your body', 'Removes carbon dioxide you don\'t need', 'Filters and warms the air you breathe', 'Works with your heart to oxygenate blood'], fun_fact: 'You breathe about 20,000 times a day without even trying.', accent: 'teal', sort_order: 3 },
  { id: uid('s4'), slug: 'digestive', name: 'Digestive System', short: 'The journey food takes — from your mouth, through your stomach and intestines, into fuel for your cells.', what_it_does: ['Breaks down food into nutrients your body can use', 'Absorbs those nutrients into your blood', 'Gets rid of what your body can\'t use', 'Is home to trillions of helpful gut bacteria'], fun_fact: 'Your digestive tract is about 30 feet long — that\'s as tall as a 3-story building laid flat.', accent: 'sunny', sort_order: 4 },
  { id: uid('s5'), slug: 'musculoskeletal', name: 'Musculoskeletal System', short: 'Your bones, muscles, and joints — the framework that holds you up and lets you move.', what_it_does: ['Bones give your body its shape and protect organs', 'Muscles contract to create movement', 'Joints let your body bend and flex', 'Stores minerals like calcium for later use'], fun_fact: 'You\'re born with about 300 bones, but some fuse together as you grow — adults have 206.', accent: 'navy', sort_order: 5 },
  { id: uid('s6'), slug: 'immune', name: 'Immune System', short: 'Your body\'s defense team — a network of cells and organs that fights off invaders and keeps you well.', what_it_does: ['Detects and destroys viruses and bacteria', 'Remembers past invaders so it can fight faster next time', 'Works quietly in the background every day', 'Includes your tonsils, spleen, and lymph nodes'], fun_fact: 'Your immune system can remember millions of different invaders — it\'s a living library.', accent: 'teal', sort_order: 6 },
  { id: uid('s7'), slug: 'endocrine', name: 'Endocrine System', short: 'A quiet messenger system of glands that release hormones — the chemical signals that guide growth, mood, and energy.', what_it_does: ['Releases hormones that control growth and mood', 'Regulates your energy and sleep cycles', 'Manages how your body uses food for fuel', 'Includes the thyroid, adrenal glands, and more'], fun_fact: 'The word "hormone" comes from a Greek word meaning "to set in motion."', accent: 'sunny', sort_order: 7 },
  { id: uid('s8'), slug: 'integumentary', name: 'Integumentary System', short: 'Your skin, hair, and nails — the protective outer layer that holds everything together.', what_it_does: ['Skin is your body\'s largest organ and first defense', 'Regulates your body temperature', 'Lets you feel touch, pressure, and temperature', 'Sheds and renews itself constantly'], fun_fact: 'You shed about 40,000 skin cells every day — your skin is brand new about every 28 days.', accent: 'navy', sort_order: 8 },
];

export const fallbackProfessions: MedicalProfession[] = [
  { id: uid('p1'), slug: 'pediatrician', name: 'Pediatrician', summary: 'A doctor who cares for babies, kids, and teens — keeping young bodies and minds healthy as they grow.', years: '11–15 years', skills: ['Patience with kids', 'Clear communication', 'Empathy', 'Problem-solving'], day_in_life: 'Morning check-ups with newborns, afternoon visits with school-age kids, and the occasional chat with a worried parent who just needs reassurance.', accent: 'teal', sort_order: 1 },
  { id: uid('p2'), slug: 'psychiatrist', name: 'Psychiatrist', summary: 'A medical doctor who specializes in mental health — diagnosing and treating conditions of the mind.', years: '12–15 years', skills: ['Active listening', 'Compassion', 'Analytical thinking', 'Patience'], day_in_life: 'A mix of talk-based therapy sessions, medication reviews, and collaborating with therapists to build care plans that fit each person.', accent: 'hotpink', sort_order: 2 },
  { id: uid('p3'), slug: 'nurse', name: 'Registered Nurse', summary: 'The heart of patient care — nurses assess, comfort, educate, and advocate for patients every single shift.', years: '4–6 years', skills: ['Calm under pressure', 'Empathy', 'Attention to detail', 'Teamwork'], day_in_life: 'Bedside care all day — checking vitals, giving medications, calming anxious patients, and catching the small changes that matter most.', accent: 'teal', sort_order: 3 },
  { id: uid('p4'), slug: 'surgeon', name: 'Surgeon', summary: 'A doctor who operates to repair injuries, remove disease, and transform lives with their hands.', years: '13–16 years', skills: ['Steady hands', 'Focus under pressure', 'Spatial reasoning', 'Stamina'], day_in_life: 'Early morning rounds, hours in the operating room with a coordinated team, then follow-up visits to see patients healing.', accent: 'navy', sort_order: 4 },
  { id: uid('p5'), slug: 'physical-therapist', name: 'Physical Therapist', summary: 'A movement expert who helps people recover from injury, manage pain, and regain strength and confidence.', years: '6–8 years', skills: ['Encouragement', 'Body knowledge', 'Patience', 'Hands-on skill'], day_in_life: 'One-on-one sessions guiding patients through exercises, celebrating small wins, and rebuilding what injury tried to take.', accent: 'sunny', sort_order: 5 },
  { id: uid('p6'), slug: 'pharmacist', name: 'Pharmacist', summary: 'A medication expert who ensures the right medicine reaches the right person — safely and effectively.', years: '6–8 years', skills: ['Precision', 'Memory', 'Communication', 'Trustworthiness'], day_in_life: 'Reviewing prescriptions, counseling patients on new medications, and double-checking that nothing interacts dangerously.', accent: 'teal', sort_order: 6 },
  { id: uid('p7'), slug: 'veterinarian', name: 'Veterinarian', summary: 'A doctor for animals — caring for pets, farm animals, and sometimes wildlife, too.', years: '8–10 years', skills: ['Love of animals', 'Adaptability', 'Gentle hands', 'Problem-solving'], day_in_life: 'Wellness exams, surgeries, dental cleanings, and lots of time reassuring pet parents — every patient has a different personality.', accent: 'sunny', sort_order: 7 },
  { id: uid('p8'), slug: 'paramedic', name: 'Paramedic', summary: 'A frontline medical hero who responds to emergencies and provides critical care in the field.', years: '2–4 years', skills: ['Fast decisions', 'Calm in chaos', 'Physical stamina', 'Compassion'], day_in_life: 'Responding to calls, stabilizing patients at the scene, and racing them to the hospital — every shift is unpredictable and vital.', accent: 'hotpink', sort_order: 8 },
  { id: uid('p9'), slug: 'medical-researcher', name: 'Medical Researcher', summary: 'A scientist who studies diseases and treatments to discover what helps — and what could change the future.', years: '8–12 years', skills: ['Curiosity', 'Persistence', 'Critical thinking', 'Data skills'], day_in_life: 'Lab experiments, analyzing results, writing up findings, and chasing the "what if" questions that could lead to the next breakthrough.', accent: 'navy', sort_order: 9 },
  { id: uid('p10'), slug: 'nutritionist', name: 'Registered Dietitian', summary: 'A food and nutrition expert who helps people eat in ways that support their health and their lives.', years: '5–7 years', skills: ['Listening', 'Encouragement', 'Science literacy', 'Cultural awareness'], day_in_life: 'Counseling sessions, personalized meal planning, and helping people build a kinder, healthier relationship with food.', accent: 'teal', sort_order: 10 },
];

export const fallbackSiteSettings: SiteSettings = {
  home: {
    heroEyebrow: 'Welcome to MY Journal',
    heroTitle: 'Your wellness',
    heroHighlight: 'cheerleader',
    heroTail: 'in your pocket.',
    heroSubtitle:
      "Check in with how you're feeling, get blogs that actually help, learn how your body works, and explore a future in medicine. Built by young people, for young people.",
    affirmations: [
      'You are allowed to take up space.',
      'Rest is part of the work.',
      'Your pace is the right pace.',
      'Feelings are visitors, not residents.',
      'Asking for help is a superpower.',
      'You are further than you were yesterday.',
    ],
    motto: 'You Got This. We mean it.',
    mottoSub: "Whatever you're carrying, you don't have to carry it alone.",
    features: [
      { title: 'Wellness Check-In', desc: "A quick, gentle survey about how you're really doing — and blogs picked just for you." },
      { title: 'Uplifting Blogs', desc: 'Real, doable advice from our team on mood, sleep, food, focus, and everything between.' },
      { title: 'Learn About Your Body', desc: 'Short, illustrated explainers on every body system — no textbook required.' },
      { title: 'Find Your Path', desc: 'Curious about a career in medicine? Discover roles that match your spark.' },
    ],
    featuresEyebrow: "What's inside",
    featuresTitle: 'Four ways MY Journal has your back',
    featuresSubtitle: 'Pick a starting point — or let the check-in choose one for you.',
    topicsEyebrow: 'We talk about',
    topicsTitle: 'Topics we cover',
    topicsSubtitle: "Whatever you're working through, there's a place to start here.",
    featuredEyebrow: 'From our team',
    featuredTitle: 'Featured reads',
    featuredSubtitle: 'Hand-picked articles to lift your day.',
    ctaTitle: 'One small step is still a step.',
    ctaSubtitle: 'Take the 2-minute check-in and get personalized reads for where you are right now.',
  },
  about: {
    eyebrow: 'About MY Journal',
    title: "We're here to remind you",
    highlight: 'You Got This.',
    paragraph:
      "Medical Youth Journal (MY Journal, for short) is a nonprofit built by young people who believe wellness should feel welcoming — not intimidating. We write about the stuff that actually matters at your age: mood, sleep, food, focus, friendships, and the big question of what to do with your life.",
    whatWeDoEyebrow: 'What we do',
    whatWeDoTitle: 'A wellness companion, not another thing to stress about',
    whatWeDoSubtitle: 'Four ways we show up for you — all free, all friendly.',
    whatWeDo: [
      { title: 'Check-In', desc: 'A 2-minute survey that meets you where you are and suggests reads that help.' },
      { title: 'Blogs', desc: 'Real advice on the things young people actually face — in plain language.' },
      { title: 'Your Body', desc: 'Illustrated explainers for every body system, minus the textbook headaches.' },
      { title: 'Find Your Path', desc: "A friendly map to medical careers for future helpers who aren't sure which way to go." },
    ],
    valuesEyebrow: 'What we believe',
    valuesTitle: 'The values behind every page',
    values: [
      { title: 'Kindness first', desc: 'No judgement, no shame. Every word here is written to lift you up, not weigh you down.' },
      { title: 'Honest info', desc: 'Content reviewed by our team and grounded in real medical understanding — explained simply.' },
      { title: 'For young people, by young people', desc: "We get what it's like because we're living it too. Your voice belongs in this conversation." },
      { title: 'Progress over perfect', desc: 'Small steps count. We celebrate the little wins that add up to real change.' },
    ],
    noteText:
      "MY Journal shares supportive information and stories — it's not a replacement for professional medical advice, diagnosis, or treatment. If you're struggling, please reach out to a trusted adult, a doctor, or a local support line. Asking for help is one of the bravest things you can do.",
    ctaTitle: 'Come as you are.',
    ctaSubtitle: "Start with a check-in, browse a blog, or just look around. There's no wrong first step.",
  },
};

export const fallback = {
  categories: fallbackCategories,
  blogs: fallbackBlogs,
  surveyQuestions: fallbackSurveyQuestions,
  bodySystems: fallbackBodySystems,
  professions: fallbackProfessions,
  siteSettings: fallbackSiteSettings,
  teamPasscodeHash: null as string | null,
};
